### ISSUE TITLE
Add order

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/warehouse-js-blocks#1]
The current functionality is just to fill an order id. 

The order id should be auto-generated.
The view should support filling-in items that are going to be in this order.

**Comment by SDinev** [comment]
Clarification on the current flow:
Adding an order does not mean generating an order. It means that there is one in a database already, and you're just calling it either via submitting the number, or via scanning a barcode.

If we keep the current flow, there is no auto-generation necessary.

**Comment by IG-Stanimir-Dimitrov** [comment]
The end-user should not be asked to manually type in the order id number.
Basically there are two use cases:

**1. The user can add an order by selecting it from a predefined list.**
Since the order must already exist, the user should see a list of available orders, search by id and select the required one. 

**2. The user can add an order by scanning a barcode.**
The end-user can add an order using the scanner as currently implemented.

The current flows must be re-worked accordingly to cover both scenarios.

**Comment by SDinev** [comment]
Hello, here comes a proposal:
To avoid creating a screen that has two further options (scan barcode or search database for orders), a better option could be to utilize the FAB button better and make it pop a small menu with the options;
1. When you hit the search icon, you are automatically prompted to write a number. You also have the first four items automatically displaying. You cannot have search history, because we don't expect people to do the same search twice.
2. When you start typing, the app suggests the first four results that match the criteria alphabetically. You can pick either by hitting the enter button on the keyboard or by choosing one of the options;
3. When you have selected an option, the button to add the order is available to complete the operation;

-- **cons** - the cons of this is that you can navigate away accidentally by tapping outside the search field/button;

![01_startpage_fab_open](https://cloud.githubusercontent.com/assets/13866657/21098855/cdf6c392-c073-11e6-8960-df2073c2a15c.png)
![01_startpage_addorder_1_start](https://cloud.githubusercontent.com/assets/13866657/21098890/14f11ae0-c074-11e6-99fe-5bc2b3aca20b.png)
![01_startpage_addorder_2_searchsuggestions](https://cloud.githubusercontent.com/assets/13866657/21098853/cdf3cf66-c073-11e6-8e35-38394a388cff.png)
![01_startpage_addorder_3_accept](https://cloud.githubusercontent.com/assets/13866657/21098857/cdf86576-c073-11e6-8342-bb661e0794c2.png)
![03_add_order_scanbarcode](https://cloud.githubusercontent.com/assets/13866657/21098856/cdf82430-c073-11e6-9667-aa83b87f4890.png)
